### ISSUE TITLE
[Bug]: mistyped in first banner?

### ISSUE THREAD

**Issue by mfathurr** [n6ai/flowrift#3]
### OS

Laptop Windows 10

### Browsers

Firefox

### Description

Thanks for this great project.
This really helps me in the process of creating a website even faster.

I want to report a typo in the banner code as I attached in the screenshot.
what is ms:px-8? i know about px-8 but i don't know about ms:? is there a typo?
![flowrift-banner](https://user-images.githubusercontent.com/23496630/212501643-d5a9f19a-f96e-4ee1-a662-52a4dfd24f31.jpg)

If I can request something, can I request a responsive fixed bottom navbar template?

I apologize for my bad English because it's not my native language.

**Comment by sergejcodes** [comment]
Hi 👋, 

this was a typo and is now fixed. It should be: `md:px-8`.

There's now a new Issue type called [🚀 New Content proposal](https://github.com/n6ai/flowrift/issues/new/choose),
You can use it to create a content (template) request, make sure to attach some example images or links.

**Comment by mfathurr** [comment]
so thats a typo.
thank you for the fixed 😊
