### ISSUE TITLE
[Content]: Request for responsive floating bottom navigation component

### ISSUE THREAD

**Issue by mfathurr** [n6ai/flowrift#4]
### Clear and concise description of the content request to be added to Flowrift. Screenshorts or links can be helpful.

Hi 👋

Once again thank you for this great project.

If can i want to request responsive floating bottom navigation component?

these are some examples:
[Example #1](https://tailwindcomponents.com/component/responsive-bottom-navigation) -> similar like i imagine but not floating
[Example #2](https://tailwindcomponents.com/component/sticky-bottom-mobile-navbar) -> similar like i imagine but not floating
[Example #3](https://kopi.dev/tailwind/bottom-navigation/) -> similar like i imagine but not floating & i don't know this is responsive or not
[Example #4](https://tailwindcomponents.com/storage/4957/conversions/temp22458-thumb.jpg) -> the shape i imagine is something like this
i wish you can make some variation from the image (Example #4).

Thank you very much.

### Validations

- [X] Check that there isn't already an issue that request the same content to avoid creating a duplicate.

**Comment by sergejcodes** [comment]
New `Floating Navigation` collection is now included in Flowrift.

**Comment by mfathurr** [comment]
I've seen the results of my request and it's very useful for me to speed up creating navigation on mobile devices.
Thank you very much for your work and help sir.
And sorry if there are words that are not quite right or not good because I use Google Translate to express my gratitude.
