### ISSUE TITLE
[Feature]: Sub Groups / Categories

### ISSUE THREAD

**Issue by adminy** [n6ai/flowrift#5]
### Clear and concise description of the content request to be added to Flowrift. Screenshorts or links can be helpful.

Menu on the left feels a little flat. It'd be really nice if there was a sense of depth, say for example header then possible components under that. same with side bar.

### Validations

- [X] Check that there isn't already an issue that request the same content to avoid creating a duplicate.

**Comment by sergejcodes** [comment]
Well, that's true, but the collections are alphabetically sorted. Currently, no Idea how to achieve a better grouping without breaking the sorting and filtering. A better solution may or may not be implemented in the future, this needs some research, it hasn't the highest priority at the moment though.
