### ISSUE TITLE
[Bug]: Class

### ISSUE THREAD

**Issue by yordiverbeeck** [n6ai/flowrift#6]
### OS

/

### Description

First of all thanks so much for making this tool, it's very handy!
This is not really a bug, more of a recommendation to follow best practices.

There is a recommended way to sort the order of classes in TailwindCSS. 
I'd advise going over the templates with a plugin like Prettier to make it standardised. 

More info: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Comment by sergejcodes** [comment]
Sorting is now implemented. Starting from version `1.4.0` all blocks are pre-formatted with `prettier-plugin-tailwindcss`
