### ISSUE TITLE
[Bug]: Content Section Number 2

### ISSUE THREAD

**Issue by LorennMarque** [n6ai/flowrift#7]
### OS

Windows 10

### Browsers

Chrome

### Description

Hello! The components are awesome and i've been using them for a while.

On the second "Content" section i have noticed that the container is missing an "xl"

  Original => <div class="mx-auto **max-w-screen-xl** px-4 md:px-8">
  Modified version => <div class="mx-auto **max-w-screen-2xl** px-4 md:px-8">

I noticed a bit of a weird margin to the left and as in the rest of the code is using "2xl" i tried using it and the image is correctly aligned now.

Before 2XL:
![image](https://github.com/n6ai/flowrift/assets/88694990/5f52bf66-6f5b-4c98-a26c-7be84818eb44)

After 2XL:
![image](https://github.com/n6ai/flowrift/assets/88694990/45a3534b-f3ec-480b-9039-58ddc813210f)

Im not sure if that was on purpose yet i wanted to let you know! Awesome job, love this components

**Comment by sergejcodes** [comment]
Hi, thanks! It is actually intentional. Content-only pages tend to be narrower. for easier readability, so it was accounting for that. It might make sense to adjust the width if used in other contexts.
